- global:
  - vaccine efficacy: 0.5
  - defaults:
    beta: 0.5
    gamma: 0.3
    initial ratio:
      s: 0.99
      i: 0.01
      r: 0
      id: 0
      v: 0


- groups:
  - name: p
    beta: 0.2
    gamma: 0.4
    subgroups:
      - name: infants
        size: 1000
        beta: 0.2
        gamma: 0.4
      - name: children
        size: 1000
      - name: adults
        size: 1000
      - name: matures
        size: 1000
        beta: 0.2
        gamma: 0.4
  - name: i
    beta: 0.2
    gamma: 0.4
    subgroups:
      - name: infants
        size: 1000
        beta: 0.2
        gamma: 0.4
      - name: children
        size: 1000
      - name: adults
        size: 1000
      - name: matures
        size: 1000
        beta: 0.2
        gamma: 0.4